require "pandarus/model_base"

# This is an autogenerated file. See readme.md.
module Pandarus
  class SisImport < ModelBase
    attr_accessor :id, :created_at, :ended_at, :updated_at, :workflow_state, :data, :progress


    def self.attribute_map
      {
        :id => {:external => "id", :container => false, :type => "Integer"},
        :created_at => {:external => "created_at", :container => false, :type => "DateTime"},
        :ended_at => {:external => "ended_at", :container => false, :type => "DateTime"},
        :updated_at => {:external => "updated_at", :container => false, :type => "DateTime"},
        :workflow_state => {:external => "workflow_state", :container => false, :type => "String"},
        :data => {:external => "data", :container => false, :type => "SisImportData"},
        :progress => {:external => "progress", :container => false, :type => "String"}

      }
    end
  end
end

